erDiagram
    %% nome_responsavel caso seje menor de idade 
    PACIENTE{
        int id PK
        char Nome
        date data_Nascimento
        char cpf 
        char cep
        char sexo
        char endereco 
        char nome_responsavel 
        int telefone

    }
    
    PROFISSIONAL{
        int id PK
        char Nome
        char profissão
        char local_trabalho
        char conselho_regional
        int Nr_conselho_regional
        int telefone
        char email
        char cpf

    }

    ATENDIMENTO{
        int id PK
        int id_paciente FK
        int id_profissional FK
        
    }

    PRONTUARIO {
        int id_profissional FK 
        int id_paciente FK 
        int id_atendimento FK
        char Nome
        date data_Nascimento
        char sexo
    }

    
    %% Relações do Atendimento

    ATENDIMENTO ||--|{ PACIENTE : possui
    ATENDIMENTO ||--|{ PROFISSIONAL : possui
    
    %% Relações do Prontuario

    PRONTUARIO  ||--|{ ATENDIMENTO  : possui
    PRONTUARIO  ||--|{ PACIENTE : possui
    
