erDiagram
    USUARIO {
        int id PK
        varchar nome
        varchar email
        varchar senha_hash
        varchar telefone
        varchar perfil
        varchar crm_conselho
        varchar especialidade
        boolean ativo
        timestamptz criado_em
    }

    PACIENTE {
        int id PK
        varchar nome
        date data_nascimento
        varchar sexo
        varchar cpf
        varchar telefone
        varchar email
        varchar nome_responsavel
        boolean ativo
        timestamptz criado_em
    }

    VINCULO {
        int id PK
        int usuario_id FK
        int paciente_id FK
        date data_inicio
        date data_fim
        boolean ativo
    }

    PRONTUARIO {
        int id PK
        int paciente_id FK
        varchar grupo_sanguineo
        text observacoes_gerais
        timestamptz criado_em
        timestamptz atualizado_em
    }

    EVOLUCAO {
        int id PK
        int prontuario_id FK
        int autor_id FK
        varchar especialidade_autor
        text descricao
        text plano_terapeutico
        varchar audio_url
        text transcricao_ia
        timestamptz criado_em
    }

    ALERGIA {
        int id PK
        int prontuario_id FK
        int registrado_por FK
        varchar substancia
        varchar reacao
        varchar gravidade
        timestamptz registrado_em
    }

    EXAME {
        int id PK
        int prontuario_id FK
        int solicitado_por FK
        varchar nome
        varchar tipo
        date data_resultado
        varchar arquivo_url
        varchar status
        timestamptz criado_em
    }

    MENSAGEM {
        int id PK
        int remetente_id FK
        int paciente_id FK
        text conteudo
        varchar tipo
        boolean lida
        timestamptz enviado_em
    }

    USUARIO ||--|{ VINCULO : "possui"
    PACIENTE ||--|{ VINCULO : "possui"
    
    PACIENTE ||--|| PRONTUARIO : "tem um único"
    
    PRONTUARIO ||--|{ EVOLUCAO : "contem"
    USUARIO ||--|{ EVOLUCAO : "escreve"
    
    PRONTUARIO ||--|{ ALERGIA : "registra"
    USUARIO ||--|{ ALERGIA : "identifica"
    
    PRONTUARIO ||--|{ EXAME : "possui"
    USUARIO ||--|{ EXAME : "solicita"
    
    USUARIO ||--|{ MENSAGEM : "envia"
    PACIENTE ||--|{ MENSAGEM : "recebe"